#!/bin/bash
# changelog.sh - Generate structured CHANGELOG.md from git history
# Bounty: $50 - claude-builders-bounty
# Usage: ./changelog.sh [--tag v1.0]

set -euo pipefail

# Configuration
OUTPUT_FILE="CHANGELOG.md"
SINCE_TAG="${1#--tag=}"
if [ -z "$SINCE_TAG" ] && [ "$1" = "--tag" ] && [ -n "$2" ]; then
    SINCE_TAG="$2"
fi

# Get repo name
REPO_NAME=$(basename "$(git rev-parse --show-toplevel)" 2>/dev/null || echo "project")

# Determine commit range
if [ -n "$SINCE_TAG" ]; then
    RANGE="${SINCE_TAG}..HEAD"
    echo "Generating changelog since tag: $SINCE_TAG"
else
    LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
    if [ -n "$LAST_TAG" ]; then
        RANGE="${LAST_TAG}..HEAD"
        echo "Generating changelog since last tag: $LAST_TAG"
    else
        RANGE="HEAD"
        echo "No tags found. Generating changelog from all commits."
    fi
fi

# Categorize commits
ADDED=$(git log "$RANGE" --oneline --grep="^feat" --grep="^add" --grep="^feature" --grep="^新增" --all-match=false 2>/dev/null || echo "")
FIXED=$(git log "$RANGE" --oneline --grep="^fix" --grep="^bug" --grep="^hotfix" --grep="^修复" --all-match=false 2>/dev/null || echo "")
CHANGED=$(git log "$RANGE" --oneline --grep="^refactor" --grep="^update" --grep="^perf" --grep="^优化" --all-match=false 2>/dev/null || echo "")
REMOVED=$(git log "$RANGE" --oneline --grep="^remove" --grep="^delete" --grep="^deprecate" --grep="^删除" --all-match=false 2>/dev/null || echo "")

# Build CHANGELOG
{
    echo "# Changelog"
    echo ""
    echo "## [$(date +%Y-%m-%d)]"
    echo ""

    if [ -n "$ADDED" ]; then
        echo "### Added"
        echo "$ADDED" | while read -r line; do
            if [ -n "$line" ]; then
                echo "- $line"
            fi
        done
        echo ""
    fi

    if [ -n "$FIXED" ]; then
        echo "### Fixed"
        echo "$FIXED" | while read -r line; do
            if [ -n "$line" ]; then
                echo "- $line"
            fi
        done
        echo ""
    fi

    if [ -n "$CHANGED" ]; then
        echo "### Changed"
        echo "$CHANGED" | while read -r line; do
            if [ -n "$line" ]; then
                echo "- $line"
            fi
        done
        echo ""
    fi

    if [ -n "$REMOVED" ]; then
        echo "### Removed"
        echo "$REMOVED" | while read -r line; do
            if [ -n "$line" ]; then
                echo "- $line"
            fi
        done
        echo ""
    fi

    echo "---"
    echo "*Generated by changelog.sh*"
} > "$OUTPUT_FILE"

echo "Done! CHANGELOG.md generated ($(wc -l < "$OUTPUT_FILE") lines)"
